In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
dataset=pd.read_csv("/content/Iris.csv")

In [ ]:
dataset

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2   
1      2            4.9           3.0            1.4           0.2   
2      3            4.7           3.2            1.3           0.2   
3      4            4.6           3.1            1.5           0.2   
4      5            5.0           3.6            1.4           0.2   
..   ...            ...           ...            ...           ...   
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  
0       Iris-setosa  
1       Iris-setosa  
2       Iris-setosa  
3       Iris-setosa  
4       Iris-setosa  
..              ...  
145  Iris-virginica  
146  Iris-virginica  
147  Iris-virginica  
148  Iris-virginica  
149  Iris-virginica  

[150 rows x 6 columns]

In [ ]:
from sklearn.preprocessing import StandardScaler

In [ ]:
scaler=StandardScaler()

In [ ]:
scaler.fit(dataset.drop('Species',axis=1))

StandardScaler()

In [ ]:
scaler_features=scaler.transform(dataset.drop('Species',axis=1))

In [ ]:
dataset.columns[:-1]

Index(['Id', 'SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm'], dtype='object')

In [ ]:
new_dataset=pd.DataFrame(scaler_features,columns=dataset.columns[:-1])

In [ ]:
new_dataset

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0   -1.720542      -0.900681      1.032057      -1.341272     -1.312977
1   -1.697448      -1.143017     -0.124958      -1.341272     -1.312977
2   -1.674353      -1.385353      0.337848      -1.398138     -1.312977
3   -1.651258      -1.506521      0.106445      -1.284407     -1.312977
4   -1.628164      -1.021849      1.263460      -1.341272     -1.312977
..        ...            ...           ...            ...           ...
145  1.628164       1.038005     -0.124958       0.819624      1.447956
146  1.651258       0.553333     -1.281972       0.705893      0.922064
147  1.674353       0.795669     -0.124958       0.819624      1.053537
148  1.697448       0.432165      0.800654       0.933356      1.447956
149  1.720542       0.068662     -0.124958       0.762759      0.790591

[150 rows x 5 columns]

In [ ]:
from sklearn.model_selection import train_test_split
X=new_dataset
y=dataset["Species"]

In [ ]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=42)

In [ ]:
from sklearn.naive_bayes import GaussianNB,BernoulliNB,CategoricalNB

In [ ]:
classifier=GaussianNB()

In [ ]:
classifier.fit(X_train,y_train)

GaussianNB()

In [ ]:
pred=classifier.predict(X_test)

In [ ]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
score=[]
score.append(accuracy_score(y_test,pred))
print(confusion_matrix(y_test,pred))


[[19  0  0]
 [ 0 13  0]
 [ 0  0 13]]


In [ ]:
print(score)

[1.0]


In [ ]:
classifier=BernoulliNB()
classifier.fit(X_train,y_train)
pred=classifier.predict(X_test)
scores=[]
scores.append(accuracy_score(y_test,pred))
print(confusion_matrix(y_test,pred))

[[19  0  0]
 [ 0  9  4]
 [ 0  1 12]]


In [ ]:
print(scores)

[0.8888888888888888]
